/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"

// ADC 1/3 -> PA3
// ADC 1 CHANNEL 3

void ADC_IRQHandler(void);

int main(void)
{

	//initialise_monitor_handles();
	printf("Semihosting rozpoczety\n");
	ADC_CONF();
	ADC_INT_CONF();
	ADC_START;

	while(1){

	}
}

void ADC_IRQHandler(void){
	result = ADC1->DR;
	if(result == 0){
		//DISPLAY ERROR MESSAGE
	} else {
		//DISPLAY RESULT OF CONVERSION
	}
}
